### ISSUE TITLE
Add standard log-in/log out functionality

### ISSUE THREAD

**Issue by SibylSchaefer** [Chronopolis-Digital-Preservation/audit-control-environment#34]
Current log-in is done on prompt and there is no noticeable way of logging out. Probably the most straightforward way of adding it would be to place a link at the top with Status, Event Log, System Settings etc. (note that area will likely be revised in a future ticket). When logged in, the text should appear "Log out" and vice versa.

**Comment by SibylSchaefer** [comment]
I need to replicate this in another instance, but on UCSD production I clicked "log in" and entered my credentials. I then clicked "log out." It appeared to log me out. When I clicked "log in" again, it appeared to log me in again without requiring me to re-enter my credentials

**Comment by lsitu** [comment]
@SibylSchaefer Yep, this is not idea with BASIC login since the behavior is controlled by the browser, which caches/carries the credentials each time while accessing the website after user logged in. The form login that I added original would fix the behavior but it causes some issue with replication server to connect to the ace-am API  endpoint, so we have to disabled form login.
Since we have both the UI and API access hosted on the same app, I don't see any good ways to work around the basic log in/log out behavior from the ace-am UI side. If we really want to have form login, I think we have to hosting the API and UI as different app so that we can have form login specifically for the UI app and basic login for ace-am API, or manipulate on the replication server side for custom form login to see whether it works, which should not be the right way to go. Just let us know if you really want us to take any actions. Thanks.

CC: @thorucsd  @rstanonik

**Comment by SibylSchaefer** [comment]
Thanks for the explanation! I think we can leave it as is for now, especially since two of the ACE instances now require VPN access.

**Comment by SibylSchaefer** [comment]
Closed per comments
